= Changelog 
:description: Bonita Test Toolkit changelog release note

== 1.0.3

* Fix an issue where json contract resources was not parsed recursively.

== 1.0.2

=== Bugfixes

* Fix an issue where some task states like `completing_activity_with_boundary` was not interpreted properly and could lead to execptions like:
```
java.lang.IllegalArgumentException: Unexpected value 'completing_activity_with_boundary'
```

== 1.0.1

=== Bugfixes

* Fix an issue where not all task states where known which could lead to execptions like:
```
java.lang.IllegalArgumentException: Unexpected value 'executing'
```
* Fix an issue where it was not possible to set a contract value to `null`
* Fix an issue where a NPE was thrown when accessing a business data aggregated `null` reference

== 1.0.0

=== New features

* Retrieve a Business Object iterator on a multi-instantiated UserTask

=== Breaking changes

* Removed `@BonitaTests` properties:
** `clearBDM` : Replaced with xref:business-data.adoc#delete-bdm-content[BonitaTestToolkit#deleteBDMContent()], can be invoked in `@BeforeAll`, `@BeforeEach` methods...etc
** `deleteProcessInstances`: Replaced with xref:process.adoc#delete-process-instances[BonitaTestToolkit#deleteProcessInstances()], can be invoked in `@BeforeAll`, `@BeforeEach` methods...etc
** `targetRuntimeURL`: Target runtime URL must be specified using the `bonita.url` system property. Default value is still _http://localhost:8080/bonita_
* Split `TaskPredicates` into `UserTaskPredicates` and `TaskPredicates`
* New `ConnectorState` and `ConnectorActivationEvent` enumerations in replacement of the `String` return type for `Connector#getState()` and `Connector#getActivationEvent()`.
* Process instance scope changes:
** It is now possible to retrieve a ProcessInstance of instances started be a `Call Activity` or an `Event Subprocess`
** It is now mandatory to use the proper ProcessInstance to retrieve tasks, timers, documents... The root ProcessInstance cannot be used anymore for children instances.

=== Bugfixes

* Fix an issue where deleting the BDM content was not waiting for the tenant to be resumed
