= Changelog
:description: Bonita Test Toolkit changelog release note

== 3.0.0

=== Breaking changes

* Test Toolkit feature activation check added. It is now required to have a license supporting the Test Toolkit feature on the target runtime.

=== New features

* Add a new method `List<ProcessInstance> getSubprocessInstances(SubprocessInstancesCriteria criteria)` on `ProcessInstance`. This new method aims at replacing the deprecated `List<ProcessInstance> getSubprocessInstances()`.

=== Bugfixes

* Fix an issue with contract file input resources and special characters encoding.

=== Dependencies updates

* `slf4j-api` updated to `2.0.13` 

== 2.0.0

=== Breaking changes

This version removes the support of Bonita 2021.1

=== New features

* Add support for Bonita 2023.2
* Processes paths coverage reports are now generated at the end of a test session. Those HTML reports let you visualize the processes execution paths covered by your tests.
See the xref:ROOT:tests-report.adoc[Tests Report] page.
* Add `DEBUG` level output for contract at process instantiation and task execution

=== Deprecated API

Paginated methods to retrieve subprocess instances and subprocess archived instances have been deprecated. 
Non paginated equivalent method should be use instead.

=== Dependencies updates

* `bonita-java-client` updated to `1.0.1`
* `slf4j-api` updated to `2.0.7` 

== 1.0.5

* Fix an issue where subprocess instances root instance was not properly filtered in `getArchivedProcessInstances` methods.

== 1.0.4

* Fix an issue where subprocess instances where not properly filtered by `rootCaseId`.

== 1.0.3

* Fix an issue where json contract resources was not parsed recursively.

== 1.0.2

=== Bugfixes

* Fix an issue where some task states like `completing_activity_with_boundary` was not interpreted properly and could lead to execptions like:
```
java.lang.IllegalArgumentException: Unexpected value 'completing_activity_with_boundary'
```

== 1.0.1

=== Bugfixes

* Fix an issue where not all task states where known which could lead to execptions like:
```
java.lang.IllegalArgumentException: Unexpected value 'executing'
```
* Fix an issue where it was not possible to set a contract value to `null`
* Fix an issue where a NPE was thrown when accessing a business data aggregated `null` reference

== 1.0.0

=== New features

* Retrieve a Business Object iterator on a multi-instantiated UserTask

=== Breaking changes

* Removed `@BonitaTests` properties:
** `clearBDM` : Replaced with xref:business-data.adoc#delete-bdm-content[BonitaTestToolkit#deleteBDMContent()], can be invoked in `@BeforeAll`, `@BeforeEach` methods...etc
** `deleteProcessInstances`: Replaced with xref:process.adoc#delete-process-instances[BonitaTestToolkit#deleteProcessInstances()], can be invoked in `@BeforeAll`, `@BeforeEach` methods...etc
** `targetRuntimeURL`: Target runtime URL must be specified using the `bonita.url` system property. Default value is still _http://localhost:8080/bonita_
* Split `TaskPredicates` into `UserTaskPredicates` and `TaskPredicates`
* New `ConnectorState` and `ConnectorActivationEvent` enumerations in replacement of the `String` return type for `Connector#getState()` and `Connector#getActivationEvent()`.
* Process instance scope changes:
** It is now possible to retrieve a ProcessInstance of instances started be a `Call Activity` or an `Event Subprocess`
** It is now mandatory to use the proper ProcessInstance to retrieve tasks, timers, documents... The root ProcessInstance cannot be used anymore for children instances.

=== Bugfixes

* Fix an issue where deleting the BDM content was not waiting for the tenant to be resumed
