= Installation
:table-caption!:
:description: Install the Bonita Test Toolkit in your development environment

[NOTE]
====
Integration tests are built upon the Bonita Test Toolkit, based on the open source https://github.com/bonitasoft/bonita-java-client[Bonita Java Client].  +
The Bonita Test Toolkit is only available for Enterprise, Performance, Efficiency, and Teamwork. editions.
====

The `bonita-test-toolkit` can be installed in three different ways. Choose the one which suits you best.

Once installed, you can start using the `bonita-test-toolkit` dependency from any Maven project. Have a look at the xref:quick-start.adoc[quick start guide] for a first hands-on.

== Installation from the Bonita Artifact Repository

The Bonita Test Toolkit is available on xref:bonita:software-extensibility:bonita-repository-access.adoc#bonita-artifact-repository[Bonita Artifact Repository] as a standard Maven dependency.

Read the xref:bonita:setup-dev-environment:configure-maven.adoc#repositories[Add a new Maven repository section] to see how to configure your Maven settings in order to access to Bonita Artifact Repository.

== Installation from the Customer Portal

The Bonita Test Toolkit dependency can also be downloaded from the https://customer.bonitasoft.com/download/request[Bonitasoft Customer Portal].

* Choose the Bonita-Subscription-2022.1-uX product and click on `Access Download Page`.
* Scroll down to the Maven repository archive and download it.
* Extract its content in your home folder in: `$USER_HOME/.m2/repository`. This is the default location of a https://maven.apache.org/settings.html#simple-values[Maven local repository]. If you are already familiar with Maven and use another local repository location, extract the content there.

== Installation from Bonita Continuous Delivery

For BCD, the `bonita-test-toolkit` dependency is already added to the bcd-dependencies images available on https://quay.io.

.Available versions
[cols="1,1"]
|===
|`bcd-dependencies:7.14.0.beta-01`
|`com.bonitasoft:bonita-test-toolkit:1.0.0.beta-01`
|`bcd-dependencies:7.14.0`
|`com.bonitasoft:bonita-test-toolkit:1.0.0.beta-01`  +
`com.bonitasoft:bonita-test-toolkit:1.0.0`
|===
