= Installation
:table-caption!:
:description: Install the Bonita Test Toolkit in your development environment

[NOTE]
====
Integration tests are built upon the Bonita Test Toolkit, based on the open source https://github.com/bonitasoft/bonita-java-client[Bonita Java Client].  +
The Bonita Test Toolkit is only available for Enterprise, Performance, Efficiency, and Teamwork. editions.
====

Once installed, you can start using the `bonita-test-toolkit` dependency from any Maven project. Have a look at the xref:quick-start.adoc[quick start guide] for a first hands-on.

== Configure Maven to access the Bonita Artifact Repository

The Bonita Test Toolkit is available on xref:{bonitaDocVersion}@bonita:software-extensibility:bonita-repository-access.adoc#bonita-artifact-repository[Bonita Artifact Repository] as a standard Maven dependency.

Read the xref:{bonitaDocVersion}@bonita:setup-dev-environment:configure-maven.adoc#repositories[Add a new Maven repository section] to see how to configure your Maven settings in order to access to Bonita Artifact Repository.
