name: Build PR preview

on:
  pull_request:
    paths:
      - 'modules/**'
      - 'antora.yml'
      - '.github/workflows/build-pr-preview.yml'
jobs:
  build_preview:
    runs-on: ubuntu-22.04
    env:
      COMPONENT_NAME: test-toolkit
      COMPONENT_VERSION: ${{ github.base_ref }} # The base_ref or target branch of the pull request in a workflow run.
      COMPONENT_BRANCH_NAME: ${{ github.head_ref }}
      # Required to pass xref validation
      BCD_BRANCHES: '3.6,4.0'
      BONITA_BRANCH: '2023.1'
      CLOUD_BRANCH: 'master'
      BONITA_BRANCH_FOR_CLOUD: '2022.1'
      BONITA_BRANCH_2021_1: '2021.1'
    steps:
      - name: Build PR preview
        uses: bonitasoft/bonita-documentation-site/.github/actions/build-pr-site/@master
        with:
          # '>' Replace newlines with spaces (folded)
          # '-' No newline at end (strip)
          build-preview-command: >-
            ./build-preview.bash --use-multi-repositories
            --start-page "${{ env.COMPONENT_VERSION }}"@"${{ env.COMPONENT_NAME }}"::process-testing-overview.adoc
            --component-with-branches "${{ env.COMPONENT_NAME }}":"${{ env.COMPONENT_BRANCH_NAME }}"
            --component-with-branches bcd:"${{ env.BCD_BRANCHES }}" 
            --component-with-branches bonita:"${{ env.BONITA_BRANCH }},${{ env.BONITA_BRANCH_FOR_CLOUD }},${{ env.BONITA_BRANCH_2021_1 }}"
            --component-with-branches cloud:"${{ env.CLOUD_BRANCH }}"
